public enum StatType {
    MAX_HEALTH,
    ARMOR,
    VEKTHAR_CONTROL,
    MOVEMENT_SPEED,
    STRENGTH,
    MAX_MANA,

    LIGHT_ATTACK_DAMAGE,
    LIGHT_ATTACK_SPEED,
    LIGHT_ATTACK_RANGE,

    HEAVY_ATTACK_DAMAGE,
    HEAVY_ATTACK_SPEED,
    HEAVY_ATTACK_RANGE,

    DASH_SPEED_MULTIPLIER,
    DASH_COOLDOWN
}
